# General
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -sg escape-time 0
set -g renumber-windows on

# Panes
## Movement
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

## Marking
bind -n M-m select-pane -m

## Pasting
bind -n M-v switch-client -T PASTE
bind -T PASTE h join-pane -h -b -s '{marked}' \; switch-client -T root
bind -T PASTE l join-pane -h    -s '{marked}' \; switch-client -T root
bind -T PASTE k join-pane -v -b -s '{marked}' \; switch-client -T root
bind -T PASTE j join-pane -v    -s '{marked}' \; switch-client -T root
bind -T PASTE Escape switch-client -T root

## Breaking
bind -n M-b break-pane

## Layout
bind -n M-p switch-client -T PANES
bind -T PANES h split-window -h -b -c "#{pane_current_path}" \; switch-client -T root
bind -T PANES l split-window -h    -c "#{pane_current_path}" \; switch-client -T root
bind -T PANES k split-window -v -b -c "#{pane_current_path}" \; switch-client -T root
bind -T PANES j split-window -v    -c "#{pane_current_path}" \; switch-client -T root
bind -T PANES e select-layout -E \; switch-client -T root
bind -T PANES o rotate-window \; switch-client -T root
bind -T PANES c select-layout even-horizontal \; switch-client -T root
bind -T PANES r select-layout even-vertical   \; switch-client -T root
bind -T PANES Escape switch-client -T root

## Resize
bind -n M-H resize-pane -L 5
bind -n M-J resize-pane -D 5
bind -n M-K resize-pane -U 5
bind -n M-L resize-pane -R 5

# Zoom
bind -n M-z resize-pane -Z

# Close
bind -n M-x kill-pane

# Windows
## Creation
bind -n M-t new-window -c "#{pane_current_path}"

## Movement
bind -n M-Left  previous-window
bind -n M-Right next-window
bind -n M-Down  swap-window -t -1 \; select-window -t -1
bind -n M-Up    swap-window -t +1 \; select-window -t +1
